display_name: FlClash

license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - FlClash
  - Clash
  - mihomo
  - Proxy

generic_name: FlClash

group: Applications/Internet

startup_notify: true
